"""empty message

Revision ID: 8b5b93ec9a0f
Revises: 791c7c9986c7
Create Date: 2021-12-20 10:01:17.796577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5b93ec9a0f'
down_revision = '791c7c9986c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'card_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
